### PR TITLE
Upgrade videojs to v7

### LINKED ISSUE #46: Support for video js 7
Are you guys going to support video js 7?

### PR DESCRIPTION
**Pull request by jackpope**
Fixes #46 

- Move to yarn for package management
- Upgrade videojs to v7.6.0 https://github.com/contently/videojs-annotation-comments/issues/46
- Update Circle ci config to use node 10.15.2
- Fixes gulp build from no-oping 
- Add semantic-release git
- Remove build files from version control

### CODE REVIEW

**Comment by aaackerman** [comment]
@jackpope do you need any eyes on new changes or help wrt testing?

**Comment by jackpope** [comment]
@aaackerman I should have some time tomorrow to look this over again and fix the dev watch command. I'll re-request your review when it is ready for another look. Thanks!

**Comment by drichar** [comment]
We're using videojs v7 and evaluating this for our core product. It looks to be exactly what we need. Let us know if we can help to get it merged!

**Comment by drichar** [comment]
Thank you!! 🎉🎉

**Comment by jackpope** [comment]
@drichar just a note on this release, somehow my `BREAKING CHANGE` commit messages didn't get picked up by semantic-release. I'm trying to move things around to get this out at v2.0.0 as there are breaking changes. Will update here when done.

**Comment by jackpope** [comment]
I've published v2.0.0 to npm and tagged here on github.

The v1.1.5 release has been removed.

Cheers! :champagne:

**Pull request merged**
